spring:
  application:
    name: spring-security-jwt
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-jwt
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
  jackson:
    mapper:
      sort-properties-alphabetically: false
  security:
    jwt:
      issue: localhost
      signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
      valid-duration: 3600 # in second
      refreshable-duration: 36000 # in seconds
server:
  servlet:
    context-path: /identity
